#!/usr/bin/env python

import logging

import tornado.ioloop
from edr_server.impl.tornado.server import make_app
from tornado.options import define, options

from edr_data_interface.dummy.dummy_interface import DummyCollectionsMetadataDataInterface, DummyEdrDataInterface

APP_LOGGER = logging.getLogger("tornado.application")

define("port", default=8808, help="port to listen on")

if __name__ == "__main__":
    tornado.options.parse_command_line()

    logging.basicConfig()
    logging.getLogger().setLevel(logging.ERROR)
    logging.getLogger("tornado").setLevel(options.logging.upper())

    data_interface = DummyEdrDataInterface(DummyCollectionsMetadataDataInterface())
    app = make_app(data_interface)
    app.listen(options.port)
    APP_LOGGER.info(f"Listening on port {options.port}...")

    tornado.ioloop.IOLoop.current().start()
